# Generated by Django 5.2 on 2025-05-22 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('numero_licencia', models.CharField(blank=True, max_length=30, null=True)),
                ('licencia_frontal', models.ImageField(blank=True, null=True, upload_to='licencias/frontal/')),
                ('licencia_trasera', models.ImageField(blank=True, null=True, upload_to='licencias/trasera/')),
                ('licencia_verificada', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20)),
                ('imagen', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=True)),
                ('precio_reserva', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('precio_renta', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
